name: null
favicon: null
layout_spectrum: 0.23958
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: 4f561355-23f7-40e9-967d-ba1874b56bff
    url: null
